version: '3.8'

services:

  postgres:
    image: postgres:16
    container_name: trading-postgres
    environment:
      POSTGRES_DB: trading_engine
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: post1234
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: trading-redis
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: trading-backend
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/trading_engine
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: post1234
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379